# Generated by Django 5.2 on 2025-04-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='URUN-0000', max_length=50, unique=True, verbose_name='Ürün Kodu'),
        ),
    ]
