# Generated by Django 4.2.7 on 2025-04-10 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_payment_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('deadline_date', models.DateField(verbose_name='Termin Tarihi')),
                ('meters', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Metre')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Tedarikçi Onayladı'), ('in_production', 'Üretimde'), ('ready', 'Hazır'), ('delivered', 'Teslim Alındı'), ('delayed', 'Gecikti'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alış Fiyatı (Metre)')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı (Metre)')),
                ('currency', models.CharField(choices=[('TL', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro')], max_length=3, verbose_name='Para Birimi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('last_status_update', models.DateTimeField(auto_now=True, verbose_name='Son Durum Güncellemesi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer', verbose_name='Müşteri')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Ürün')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-order_date'],
            },
        ),
    ]
