# Generated by Django 4.2.7 on 2025-04-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_supplier_options_supplier_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('₺', '₺ (TL)'), ('$', '$ (USD)'), ('€', '€ (EUR)')], max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='products.product', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('₺', '₺ (TL)'), ('$', '$ (USD)'), ('€', '€ (EUR)')], max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('₺', '₺ (TL)'), ('$', '$ (USD)'), ('€', '€ (EUR)')], default='TL', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('₺', '₺ (TL)'), ('$', '$ (USD)'), ('€', '€ (EUR)')], max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product', verbose_name='Ürün'),
        ),
    ]
